kind: pipeline
name: default

steps:
  - name: build
    image: docker:19.03 
    commands:
      - docker build -t aminetudo/pyomo .
      - docker run aminetudo/test_ci python app.py

  - name: docker_build
    image: docker:19.03 
    commands:
      - docker build -t aminetudo/pyomo .
      - docker login -u yourusername -p docker_password
      - docker push aminetudo/test_ci
